version: "3.8"

services:
    # Service untuk PHP
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: suritex_finance_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
        networks:
            - laravel

    # Service untuk Nginx
    web:
        image: nginx:alpine
        container_name: suritex_finance_web
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        networks:
            - laravel

networks:
    laravel:
